// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuIogxbnHH2xXinB7VkbIT_d_ZXb9NiO0',
    appId: '1:819903404890:web:7329daabda45829b34f163',
    messagingSenderId: '819903404890',
    projectId: 'recomededsystem',
    authDomain: 'recomededsystem.firebaseapp.com',
    storageBucket: 'recomededsystem.firebasestorage.app',
    measurementId: 'G-JS9LF9Z3LV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwlnwaEij2Pfp599ZsRQrNFrvLeYwen2w',
    appId: '1:819903404890:android:d5362c4b26cd8cab34f163',
    messagingSenderId: '819903404890',
    projectId: 'recomededsystem',
    storageBucket: 'recomededsystem.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBp0x8DOEdMmLwbWplC3kuR-QIpTQ4uFuQ',
    appId: '1:819903404890:ios:81efde709a8c415834f163',
    messagingSenderId: '819903404890',
    projectId: 'recomededsystem',
    storageBucket: 'recomededsystem.firebasestorage.app',
    iosBundleId: 'com.example.recomendedSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBp0x8DOEdMmLwbWplC3kuR-QIpTQ4uFuQ',
    appId: '1:819903404890:ios:81efde709a8c415834f163',
    messagingSenderId: '819903404890',
    projectId: 'recomededsystem',
    storageBucket: 'recomededsystem.firebasestorage.app',
    iosBundleId: 'com.example.recomendedSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuIogxbnHH2xXinB7VkbIT_d_ZXb9NiO0',
    appId: '1:819903404890:web:430a00302bd4a26734f163',
    messagingSenderId: '819903404890',
    projectId: 'recomededsystem',
    authDomain: 'recomededsystem.firebaseapp.com',
    storageBucket: 'recomededsystem.firebasestorage.app',
    measurementId: 'G-50GJV7TR53',
  );
}
